----- CREATE DATABASE -----
CREATE DATABASE QuanLyHangHoaDB;

USE QuanLyHangHoaDB;

----- CREATE TABLES -----
CREATE TABLE NHACUNGCAP (
  MANCC VARCHAR(5) NOT NULL,
  TENNCC VARCHAR(20),
  TRANGTHAI NUMERIC(2, 0),
  THANHPHO VARCHAR(30)
);

CREATE TABLE VANCHUYEN (
  MANCC VARCHAR(5) NOT NULL,
  MAPT VARCHAR(5) NOT NULL,
  SOLUONG NUMERIC(5, 0)
);

CREATE TABLE PHUTUNG (
  MAPT VARCHAR(5) NOT NULL,
  TENPT VARCHAR(10),
  MAUSAC VARCHAR(10),
  KHOILUONG FLOAT,
  THANHPHO VARCHAR(30)
);

----- ADD PRIMARY KEY ----- 
ALTER TABLE NHACUNGCAP ADD CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MANCC);

ALTER TABLE VANCHUYEN ADD CONSTRAINT PK_VANCHUYEN PRIMARY KEY (MAPT, MANCC);

ALTER TABLE PHUTUNG ADD CONSTRAINT PK_PHUTUNG PRIMARY KEY (MAPT);

----- ADD FOREIGN KEY -----
ALTER TABLE VANCHUYEN ADD CONSTRAINT FK_VANCHUYEN_NHACUNGCAP FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP (MANCC);

ALTER TABLE VANCHUYEN ADD CONSTRAINT FK_VANCHUYEN_PHUTUNG FOREIGN KEY (MAPT) REFERENCES PHUTUNG (MAPT);
